//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aikashka.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aikashka.Core.Data.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira.
        /// </summary>
        internal static string AikashkaName {
            get {
                return ResourceManager.GetString("AikashkaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira; bot.
        /// </summary>
        internal static string AikashkaNames {
            get {
                return ResourceManager.GetString("AikashkaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no words..
        /// </summary>
        internal static string EmptyResponseText {
            get {
                return ResourceManager.GetString("EmptyResponseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current list of users in the channel:.
        /// </summary>
        internal static string PromptChannelMembers {
            get {
                return ResourceManager.GetString("PromptChannelMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History has been cleared..
        /// </summary>
        internal static string PromptHistoryCleared {
            get {
                return ResourceManager.GetString("PromptHistoryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response should be in English..
        /// </summary>
        internal static string PromptLanguage {
            get {
                return ResourceManager.GetString("PromptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *something strange* .
        /// </summary>
        internal static string PromptUnableToHear {
            get {
                return ResourceManager.GetString("PromptUnableToHear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shut; calm.
        /// </summary>
        internal static string ShutUpWords {
            get {
                return ResourceManager.GetString("ShutUpWords", resourceCulture);
            }
        }
    }
}
